### PR TITLE
WIP Rework of the jqwik homepage

### LINKED ISSUE #82: Rework jqwik.net Homepage
Following the discussion with @luvarqpp in https://github.com/jlink/jqwik/issues/81#issuecomment-567834207 a rework of jqwik.net seems necessary.

### PR DESCRIPTION
**Pull request by luvarqpp**
## Overview

Homepage was a bit confusing to me (subjective metrics). As stated in #82, I am proposing change.

### Details

closes #82

Currently work in progress (draft pull request). I would like to get some feedback of proposed structure and style of first two paragraphs. Perhaps any suggestion to change of structure.

---

I hereby agree to the terms of the [jqwik Contributor Agreement](https://github.com/jlink/jqwik/blob/master/CONTRIBUTING.md#jqwik-contributor-agreement).

### CODE REVIEW

**Comment by jlink** [comment]
@luvarqpp Many thanks for the effort! Highly appreciated!

I'm still on the fence about using a "story telling" approach (as in section "Brief introduction to PBT") for the first contact on a landing page. Is there a library that you consider good - or even very good - where you've seen something similiar. Getting inspiration from other OSS projects might prove worthwhile here.

My personal take would be to improve the introductory example in a way to make the textual introduction mostly redundant. I love to see the bare minimum example for a lib at first glance. But maybe that's just my personal preference and most other people are different.

**Comment by luvarqpp** [comment]
Possible inspirations:

* https://www.scalacheck.org/ -> remove news and can serve as skeleton
* http://www.slf4j.org/manual.html -> as landing page, I like that after "hello world" example, there are also other "next step to advanced" examples.
* WIP, I will search for a few others...

PS: I see it also like you.

**Comment by jlink** [comment]
#scalacheck: Yes. Something like

1. What is jqwik (1 sentence)
2. Intro to PBT (2-4 sentences)
3. Quickstart
     with code example
4. Where to go from here
    - References and Supporting Material
    - How to contribute
    - ...

**Comment by jlink** [comment]
@luvarqpp Are you still interested/motivated working on this one?

**Pull request closed without merging**
