### PR TITLE
Issue 47 Convert float to String to avoid implicit double conversion …

### PR DESCRIPTION
**Pull request by blairdye**
…in BigDecimal construction

## Overview

_Formulate the problem / feature your pull request is aiming at_

### Details

_Give any necessary details about your code that is not obvious from the code itself._

_List open issues and remaining problems with your solution._

---

I hereby agree to the terms of the [jqwik Contributor Agreement](https://github.com/jlink/jqwik/blob/master/CONTRIBUTING.md#jqwik-contributor-agreement).

### CODE REVIEW

**Comment by jlink** [comment]
Looks good to me. 

Would you mind doing same thing for doubles for the sake of symmetry?

**Comment by jlink** [comment]
@blairdye Thanks again. Pull request included in current snapshot. 
I mentioned you in [release notes](https://jqwik.net/release-notes.html#111-snapshot). Hope that's fine with you.

**Comment by blairdye** [comment]
No problem I'm interested in contributing further though time is limited.
I'll have a sniff around try and find something small to start with unless
you have a suggestion?

**Comment by jlink** [comment]
Clean up, javadoc and improved documentation are the obvious candidates. If you’d rather go for functional changes I could put up a few up-for-grab issues depending on how deep you want to dive into the codebase.

**Comment by blairdye** [comment]
Not deep just now, clean up would suit. Do you have a coding standards
template so our autoformat styles are aligned?

**Comment by jlink** [comment]
Yes, but only for IntelliJ: 
https://github.com/jlink/jqwik/blob/master/jqwik-intellij-codeformatting.xml

**Pull request merged**
