### PR TITLE
Simplify CI badge in README

### PR DESCRIPTION
**Pull request by vlsi**
## Overview

The table in UI looks cluttered.

### CODE REVIEW

**Comment by jlink** [comment]
How does javadoc.io collect the javadoc? IMO only Javadoc for api packages should be published. Is there a way to influence that? If not I tend to leave the link to javadoc.io out.

**Comment by vlsi** [comment]
It fetches javadocs from Central.

I've updated the badge link to http://javadoc.io/badge/net.jqwik/jqwik-api.svg, so now it properly links to jqwik-api javadocs.
See preview at https://github.com/vlsi/jqwik/tree/patch-1

**Comment by jlink** [comment]
With the current javadoc link we're missing the optional modules `web` and `time`.
Why not link to https://jqwik.net/docs/1.7.2/javadoc/index.html or https://jqwik.net/docs/current/javadoc/index.html?

**Comment by vlsi** [comment]
I've updated the link

**Comment by jlink** [comment]
@vlsi Thanks!

**Pull request merged**
