### PR TITLE
initilize constants thread safe

### PR DESCRIPTION
**Pull request by Danny02**
## Overview

I want to use Jqwik Arbitraries in normal JUnit test to generate some example data. I get errors when I run those test in parallel, because Jqwik does not initialize constants (e.g. Provider) in a thread safe way.

---

I hereby agree to the terms of the [jqwik Contributor Agreement](https://github.com/jlink/jqwik/blob/master/CONTRIBUTING.md#jqwik-contributor-agreement).

### CODE REVIEW

**Comment by jlink** [comment]
Hi @Danny02! thanks for the PR. I obviously did not think about parallel execution when implementing most of the static initializers. :-(

However, I always try to steer clear off static initializer blocks since one has no control over when they are being executed - and initialization may be costly.

Thus, I'd prefer to make the accessor methods `synchronized` as it already is in class `RegisteredLifecycleHooks`. Would you be willing to make that change?

**Comment by Danny02** [comment]
Hi,

in the end it is of course your decision, but I'm under the impression that in this case static initializers may be the better solution. (I may have forgotten to make the fields final)

* static initializers are run the first time the class is used (in the JVM at least). In the case of those classes, the runtime behavior will not change, because the only functionality they have are the collection getters (which are the first interaction with those classes). (see [Effective Java, Joshua Bloch](https://www.kea.nu/files/textbooks/new/Effective%20Java%20%282017%2C%20Addison-Wesley%29.pdf) p. 334)
* they are thread-safe because the JVM guarantees, that they are called only once and before any further interaction with the class
* synchronized introduces a probably neglectable runtime cost

**Comment by jlink** [comment]
Yes, I've re-read about static initializers and their pros and cons. 

Performance will probably not change with normal jqwik usage but when running individual jqwik tests since many do not need all the loaded services. But the real reason is my dislike for losing control over the exact time static initializers are executed.

So my current call is going for synchronized. Which does not exclude changing my mind sometime in the future.

**Comment by Danny02** [comment]
ok, will do the changes

**Comment by jlink** [comment]
Thanks!

**Comment by jlink** [comment]
Looks very good. Thank you!

**Comment by jlink** [comment]
Just published "1.3.4-SNAPSHOT" with this PR included

**Comment by jlink** [comment]
Is now available in release 1.3.4

**Pull request merged**
