### PR TITLE
Generation of DateTimes 3) Date based methods part 2

### PR DESCRIPTION
**Pull request by zinki97**
See #175 

In this step all date-based methods are implemented

### CODE REVIEW

**Comment by zinki97** [comment]
Just waiting for decision about `leapYear` methods.

**Comment by jlink** [comment]
> Just waiting for decision about `leapYear` methods.

Remove it. Less is better by default. And it can be added without much hassle later if it shows to be worthwhile.

**Comment by zinki97** [comment]
This PR is ready for review/merging.

**Comment by jlink** [comment]
> This PR is ready for review/merging.

You are too fast for me.

**Pull request merged**
